{% set name = "acme" %}
{% set version = "1.28.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/acme-{{ version }}.tar.gz
  sha256: 1f822d0f1a4140606c7569333dba97a6df32c17bd0cc996bcdebdf611ee1d589

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - cryptography >=2.5.0
    - josepy >=1.13.0
    - pyopenssl >=17.3.0
    - pyrfc3339
    - python >=3.7
    - pytz >=2019.3
    - requests >=2.20.0
    - requests-toolbelt >=0.3.0
    - setuptools >=41.6.0

test:
  imports:
    - acme
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/letsencrypt/letsencrypt
  summary: ACME protocol implementation in Python
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - nehaljwani
