{% set name = "acme" %}
{% set version = "1.20.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/acme-{{ version }}.tar.gz
  sha256: 0ddfde8d8e574d35af2bf1d1648b6bdb359c82e257e39d6b074e35136777016e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - cryptography >=2.1.4
    - josepy >=1.1.0
    - pyopenssl >=17.3.0
    - pyrfc3339
    - python >=3.6
    - pytz
    - requests >=2.14.2
    - requests-toolbelt >=0.3.0
    - setuptools >=39.0.1

test:
  imports:
    - acme
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/letsencrypt/letsencrypt
  summary: ACME protocol implementation in Python
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - nehaljwani
