{% set name = "acme" %}
{% set version = "1.24.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/acme-{{ version }}.tar.gz
  sha256: 63161f442d7c995313305663ad2eef6b3f770899c3f635e1c1f1d0141696b298

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - cryptography >=2.5.0
    - josepy >=1.10.0
    - pyopenssl >=17.3.0
    - pyrfc3339
    - python >=3.6
    - pytz
    - requests >=2.14.2
    - requests-toolbelt >=0.3.0
    - setuptools >=39.0.1

test:
  imports:
    - acme
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/letsencrypt/letsencrypt
  summary: ACME protocol implementation in Python
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - nehaljwani
