{% set name = "acme" %}
{% set version = "1.17.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/acme-{{ version }}.tar.gz
  sha256: 2af48e40679103212532cb3d220df444207e5e7b532e0ccebe7773792e0f320e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - cryptography >=2.1.4
    - josepy >=1.1.0
    - pyopenssl >=17.3.0
    - pyrfc3339
    - python >=3.6
    - pytz
    - requests >=2.6.0
    - requests-toolbelt >=0.3.0
    - setuptools >=39.0.1

test:
  imports:
    - acme
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/letsencrypt/letsencrypt
  summary: ACME protocol implementation in Python
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - nehaljwani
